services:
  _defaults:
    autowire: true
    bind:
      $root_path: '%core.root_path%'
      $adm_relative_path: '%core.adm_relative_path%'
      $php_ext: '%core.php_ext%'
      $tables: '%tables%'
  dmzx.newsletter.controller.acp:
    class: 'dmzx\newsletter\controller\acp_controller'